sudo: required
language: python
services:
- docker

script:
- docker image build -t kazirys21/dockertest .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push kazirys21/dockertest1
  #test


# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-778174316429"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY